name: rostelekom_test
services:
  rabbitmq:
    image: rabbitmq:management
    ports:
    - ${RABBITMQ_SERVER_PORT}:5672
    - ${RABBITMQ_CLIENT_PORT}:15672
    volumes:
    - rabbitmq-data:/var/lib/rabbitmq
    env_file:
    - ./.env
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status" ]
      interval: 30s
      timeout: 10s
      retries: 3
  service_a:
    build:
      context: ../../backend/service_a
      dockerfile: ./Dockerfile
    ports:
      - ${SERVICE_A_PORT}:7777
volumes:
  rabbitmq-data: